import type { ComponentEntry } from '@/lib/wizard-store'

type Format = 'designrules' | 'claude' | 'copilot'

interface AiInstructionsInput {
  format: Format
  tokenOverrides: Record<string, string>
  components: ComponentEntry[]
}

export function buildAiInstructions({ format, tokenOverrides, components }: AiInstructionsInput): string {
  const tokenSection =
    Object.keys(tokenOverrides).length > 0
      ? `## Design Tokens\n\n${Object.entries(tokenOverrides).map(([k, v]) => `- \`--${k}\`: ${v}`).join('\n')}`
      : ''

  const compSection =
    components.length > 0
      ? `## Components\n\n${components.map((c) => `### ${c.name}\n${c.notes ? `> ${c.notes}\n` : ''}- States: ${c.states.join(', ')}\n- Variants: ${c.variants.join(', ')}`).join('\n\n')}`
      : ''

  const body = [tokenSection, compSection].filter(Boolean).join('\n\n')

  if (format === 'designrules') {
    return `# Design System Rules\n\nGenerated by Figma Design System Wizard.\n\n${body}\n`
  }

  if (format === 'claude') {
    return `# CLAUDE.md\n\nThis project uses a Figma-extracted design system. Refer to \`design-system/\` for tokens and \`components/\` for generated component code.\n\n${body}\n`
  }

  // copilot
  return `# GitHub Copilot Instructions\n\nThis project uses a Figma-extracted design system.\n\n${body}\n`
}
