import JSZip from 'jszip'
import type { ComponentEntry } from '@/lib/wizard-store'

interface ZipInput {
  showcaseHtml: string
  tokenOverrides: Record<string, string>
  components: ComponentEntry[]
}

export async function buildZip({ showcaseHtml, tokenOverrides, components }: ZipInput): Promise<Uint8Array> {
  const zip = new JSZip()

  // Showcase
  zip.file('showcase/components.html', showcaseHtml || '<p>No showcase generated.</p>')

  // Token overrides as CSS variables
  if (Object.keys(tokenOverrides).length > 0) {
    const cssLines = [':root {', ...Object.entries(tokenOverrides).map(([k, v]) => `  --${k}: ${v};`), '}']
    zip.file('design-system/tokens.css', cssLines.join('\n'))
  }

  // Component stubs
  const compsFolder = zip.folder('components')!
  for (const comp of components) {
    if (comp.generated) {
      const filename = `${comp.name.toLowerCase().replace(/\s+/g, '-')}.html`
      compsFolder.file(filename, `<!-- ${comp.name} component -->\n`)
    }
  }

  // README
  zip.file('README.md', `# Design System Export\n\nGenerated by Figma Design System Wizard.\n\n## Files\n\n- \`showcase/components.html\` — component gallery\n- \`design-system/tokens.css\` — CSS custom properties\n- \`components/\` — individual component HTML files\n`)

  return zip.generateAsync({ type: 'uint8array' })
}
